Fix etc/org.opendaylight.daexim.cfg missing from feature
Big ACK to Tx Stephen Kitt for the hint re. *s suffix

This fixes the Failed to load property file: [...]/etc/org.opendaylight.daexim.cfg
java.io.FileNotFoundException: [...]/etc/org.opendaylight.daexim.cfg (No such file or directory)

Change-Id: Iac2f38f4f57227180fcb6f58e7fe330994bb1579
Signed-off-by: Michael Vorburger <vorburger@redhat.com>